### ISSUE TITLE
Next Steps 

### ISSUE THREAD

**Issue by pratikkabade** [trvswgnr/burnout-meter#1]
After 
```
4. Create a GitHub secret for each of the following:
```

what are the next steps?

**Comment by trvswgnr** [comment]
@pratikkabade you add your secrets to your GitHub repo:

1. In your repository, go to Settings
1. Under "Security", expand the "Secrets variables" dropdown, then select "Actions"
1. Click the green "New repository secret" button
1. Add the name of the secret, and the value
1. Repeat steps 2 & 3 for each secret

Let me know if that helps!

**Comment by pratikkabade** [comment]
@trvswgnr yes, I've already did that but how to add it in twitter bio?

**Comment by trvswgnr** [comment]
@pratikkabade after adding the keys, the Action should run every 6 hours automatically. You can check the Actions tab of your repo to see the workflow run history. You can also manually run it using the workflow dispatch.
